# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditAdmin(object):
    def setupUi(self, EditAdmin):
        EditAdmin.setObjectName("EditAdmin")
        EditAdmin.resize(495, 390)
        EditAdmin.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.pict = QtWidgets.QLabel(EditAdmin)
        self.pict.setGeometry(QtCore.QRect(210, 10, 81, 91))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.pict.setFont(font)
        self.pict.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.pict.setText("")
        self.pict.setObjectName("pict")
        self.cin_hist = QtWidgets.QPushButton(EditAdmin)
        self.cin_hist.setGeometry(QtCore.QRect(10, 230, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.cin_hist.setFont(font)
        self.cin_hist.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 255, 255), stop:0.373134 rgba(62, 188, 255, 255), stop:0.985075 rgba(0, 0, 255, 255));")
        self.cin_hist.setObjectName("cin_hist")
        self.rest_hist = QtWidgets.QPushButton(EditAdmin)
        self.rest_hist.setGeometry(QtCore.QRect(10, 180, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.rest_hist.setFont(font)
        self.rest_hist.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 255, 255), stop:0.373134 rgba(62, 188, 255, 255), stop:0.985075 rgba(0, 0, 255, 255));")
        self.rest_hist.setObjectName("rest_hist")
        self.name = QtWidgets.QLabel(EditAdmin)
        self.name.setGeometry(QtCore.QRect(220, 110, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(13)
        self.name.setFont(font)
        self.name.setStyleSheet("color: rgb(255, 255, 255);")
        self.name.setObjectName("name")
        self.edit_base = QtWidgets.QPushButton(EditAdmin)
        self.edit_base.setGeometry(QtCore.QRect(260, 180, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.edit_base.setFont(font)
        self.edit_base.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 255, 255), stop:0.373134 rgba(62, 188, 255, 255), stop:0.985075 rgba(0, 0, 255, 255));")
        self.edit_base.setObjectName("edit_base")
        self.edit_foods = QtWidgets.QPushButton(EditAdmin)
        self.edit_foods.setGeometry(QtCore.QRect(260, 230, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.edit_foods.setFont(font)
        self.edit_foods.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 255, 255), stop:0.373134 rgba(62, 188, 255, 255), stop:0.985075 rgba(0, 0, 255, 255));")
        self.edit_foods.setObjectName("edit_foods")
        self.full_food = QtWidgets.QPushButton(EditAdmin)
        self.full_food.setGeometry(QtCore.QRect(130, 280, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.full_food.setFont(font)
        self.full_food.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 255, 255), stop:0.373134 rgba(62, 188, 255, 255), stop:0.985075 rgba(0, 0, 255, 255));")
        self.full_food.setObjectName("full_food")
        self.full_films = QtWidgets.QPushButton(EditAdmin)
        self.full_films.setGeometry(QtCore.QRect(130, 330, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        self.full_films.setFont(font)
        self.full_films.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 255, 255), stop:0.373134 rgba(62, 188, 255, 255), stop:0.985075 rgba(0, 0, 255, 255));")
        self.full_films.setObjectName("full_films")

        self.retranslateUi(EditAdmin)
        QtCore.QMetaObject.connectSlotsByName(EditAdmin)

    def retranslateUi(self, EditAdmin):
        _translate = QtCore.QCoreApplication.translate
        EditAdmin.setWindowTitle(_translate("EditAdmin", "Админ Панель"))
        self.cin_hist.setText(_translate("EditAdmin", "Просмотреть историю просмотра\n"
"кино"))
        self.rest_hist.setText(_translate("EditAdmin", "Просмотреть историю заказов"))
        self.name.setText(_translate("EditAdmin", "admin"))
        self.edit_base.setText(_translate("EditAdmin", "Редактировать базу данных\n"
"о пользователях"))
        self.edit_foods.setText(_translate("EditAdmin", "Редактировать меню\n"
"ресторана"))
        self.full_food.setText(_translate("EditAdmin", "Просмотреть базу данных о\n"
"всех заказах"))
        self.full_films.setText(_translate("EditAdmin", "Просмотреть базу данных о\n"
"всех просмотрах кино"))
