# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_user_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeUserBase(object):
    def setupUi(self, ChangeUserBase):
        ChangeUserBase.setObjectName("ChangeUserBase")
        ChangeUserBase.resize(717, 186)
        ChangeUserBase.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.label = QtWidgets.QLabel(ChangeUserBase)
        self.label.setGeometry(QtCore.QRect(10, 30, 241, 31))
        self.label.setStyleSheet("font: 57 14pt \"Montserrat Medium\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.name = QtWidgets.QLineEdit(ChangeUserBase)
        self.name.setGeometry(QtCore.QRect(260, 31, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.name.setFont(font)
        self.name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name.setText("")
        self.name.setObjectName("name")
        self.all_users = QtWidgets.QPushButton(ChangeUserBase)
        self.all_users.setGeometry(QtCore.QRect(10, 90, 221, 51))
        self.all_users.setStyleSheet("font: 57 9pt \"Montserrat Medium\"; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 255, 255), stop:0.373134 rgba(62, 188, 255, 255), stop:0.985075 rgba(0, 0, 255, 255));")
        self.all_users.setObjectName("all_users")
        self.delete_2 = QtWidgets.QPushButton(ChangeUserBase)
        self.delete_2.setGeometry(QtCore.QRect(562, 80, 131, 41))
        self.delete_2.setStyleSheet("font: 57 14pt \"Montserrat Medium\"; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 255, 255), stop:0.373134 rgba(62, 188, 255, 255), stop:0.985075 rgba(0, 0, 255, 255));")
        self.delete_2.setObjectName("delete_2")
        self.update_user = QtWidgets.QPushButton(ChangeUserBase)
        self.update_user.setGeometry(QtCore.QRect(500, 130, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.update_user.setFont(font)
        self.update_user.setStyleSheet("font: 57 11pt \"Montserrat Medium\"; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 255, 255), stop:0.373134 rgba(62, 188, 255, 255), stop:0.985075 rgba(0, 0, 255, 255));")
        self.update_user.setObjectName("update_user")
        self.error = QtWidgets.QLabel(ChangeUserBase)
        self.error.setGeometry(QtCore.QRect(250, 90, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.error.setFont(font)
        self.error.setStyleSheet("color: rgb(255, 255, 255);")
        self.error.setText("")
        self.error.setObjectName("error")

        self.retranslateUi(ChangeUserBase)
        QtCore.QMetaObject.connectSlotsByName(ChangeUserBase)

    def retranslateUi(self, ChangeUserBase):
        _translate = QtCore.QCoreApplication.translate
        ChangeUserBase.setWindowTitle(_translate("ChangeUserBase", "Изменить базу данных"))
        self.label.setText(_translate("ChangeUserBase", "Имя пользователя:"))
        self.all_users.setText(_translate("ChangeUserBase", "Просмотреть базу\n"
"данных о пользователях"))
        self.delete_2.setText(_translate("ChangeUserBase", "Удалить"))
        self.update_user.setText(_translate("ChangeUserBase", "Обновить данные"))
