# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_user_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeUser(object):
    def setupUi(self, ChangeUser):
        ChangeUser.setObjectName("ChangeUser")
        ChangeUser.resize(517, 353)
        ChangeUser.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.result = QtWidgets.QLabel(ChangeUser)
        self.result.setGeometry(QtCore.QRect(18, 300, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.result.setFont(font)
        self.result.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.result.setStyleSheet("color: rgb(255, 255, 255);")
        self.result.setText("")
        self.result.setObjectName("result")
        self.name_label = QtWidgets.QLabel(ChangeUser)
        self.name_label.setGeometry(QtCore.QRect(8, 10, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(15)
        self.name_label.setFont(font)
        self.name_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.name_label.setObjectName("name_label")
        self.name = QtWidgets.QLineEdit(ChangeUser)
        self.name.setGeometry(QtCore.QRect(8, 50, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(13)
        self.name.setFont(font)
        self.name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.name.setObjectName("name")
        self.email = QtWidgets.QLineEdit(ChangeUser)
        self.email.setGeometry(QtCore.QRect(8, 230, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(13)
        self.email.setFont(font)
        self.email.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.email.setObjectName("email")
        self.pass_label = QtWidgets.QLabel(ChangeUser)
        self.pass_label.setGeometry(QtCore.QRect(8, 100, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(15)
        self.pass_label.setFont(font)
        self.pass_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.pass_label.setObjectName("pass_label")
        self.password = QtWidgets.QLineEdit(ChangeUser)
        self.password.setGeometry(QtCore.QRect(8, 140, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(13)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.password.setObjectName("password")
        self.email_label = QtWidgets.QLabel(ChangeUser)
        self.email_label.setGeometry(QtCore.QRect(8, 190, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(15)
        self.email_label.setFont(font)
        self.email_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.email_label.setObjectName("email_label")
        self.change = QtWidgets.QPushButton(ChangeUser)
        self.change.setGeometry(QtCore.QRect(340, 290, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(13)
        self.change.setFont(font)
        self.change.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 255, 255), stop:0.373134 rgba(62, 188, 255, 255), stop:0.985075 rgba(0, 0, 255, 255));")
        self.change.setObjectName("change")

        self.retranslateUi(ChangeUser)
        QtCore.QMetaObject.connectSlotsByName(ChangeUser)

    def retranslateUi(self, ChangeUser):
        _translate = QtCore.QCoreApplication.translate
        ChangeUser.setWindowTitle(_translate("ChangeUser", "Изменить данные"))
        self.name_label.setText(_translate("ChangeUser", "Имя пользователя:"))
        self.pass_label.setText(_translate("ChangeUser", "Пароль:"))
        self.email_label.setText(_translate("ChangeUser", "Email:"))
        self.change.setText(_translate("ChangeUser", "Изменить"))
