# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changing.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Change(object):
    def setupUi(self, Change):
        Change.setObjectName("Change")
        Change.setEnabled(True)
        Change.resize(517, 353)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Change.sizePolicy().hasHeightForWidth())
        Change.setSizePolicy(sizePolicy)
        Change.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Change.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.name_label = QtWidgets.QLabel(Change)
        self.name_label.setGeometry(QtCore.QRect(10, 10, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(15)
        self.name_label.setFont(font)
        self.name_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.name_label.setObjectName("name_label")
        self.name = QtWidgets.QLineEdit(Change)
        self.name.setGeometry(QtCore.QRect(10, 50, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(13)
        self.name.setFont(font)
        self.name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.name.setObjectName("name")
        self.pass_label = QtWidgets.QLabel(Change)
        self.pass_label.setGeometry(QtCore.QRect(10, 100, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(15)
        self.pass_label.setFont(font)
        self.pass_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.pass_label.setObjectName("pass_label")
        self.password = QtWidgets.QLineEdit(Change)
        self.password.setGeometry(QtCore.QRect(10, 140, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(13)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.password.setObjectName("password")
        self.email_label = QtWidgets.QLabel(Change)
        self.email_label.setGeometry(QtCore.QRect(10, 190, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(15)
        self.email_label.setFont(font)
        self.email_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.email_label.setObjectName("email_label")
        self.email = QtWidgets.QLineEdit(Change)
        self.email.setGeometry(QtCore.QRect(10, 230, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(13)
        self.email.setFont(font)
        self.email.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.email.setObjectName("email")
        self.change = QtWidgets.QPushButton(Change)
        self.change.setGeometry(QtCore.QRect(342, 290, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(13)
        self.change.setFont(font)
        self.change.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 255, 255), stop:0.373134 rgba(62, 188, 255, 255), stop:0.985075 rgba(0, 0, 255, 255));")
        self.change.setObjectName("change")
        self.result = QtWidgets.QLabel(Change)
        self.result.setGeometry(QtCore.QRect(20, 300, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.result.setFont(font)
        self.result.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.result.setStyleSheet("color: rgb(255, 255, 255);")
        self.result.setText("")
        self.result.setObjectName("result")

        self.retranslateUi(Change)
        QtCore.QMetaObject.connectSlotsByName(Change)

    def retranslateUi(self, Change):
        _translate = QtCore.QCoreApplication.translate
        Change.setWindowTitle(_translate("Change", "Смена данных"))
        self.name_label.setText(_translate("Change", "Имя пользователя:"))
        self.pass_label.setText(_translate("Change", "Пароль:"))
        self.email_label.setText(_translate("Change", "Email:"))
        self.change.setText(_translate("Change", "Изменить"))
