# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cin_hist.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CinHist(object):
    def setupUi(self, CinHist):
        CinHist.setObjectName("CinHist")
        CinHist.resize(548, 533)
        CinHist.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.orders = QtWidgets.QTableWidget(CinHist)
        self.orders.setGeometry(QtCore.QRect(10, 10, 531, 511))
        self.orders.setMaximumSize(QtCore.QSize(531, 511))
        self.orders.setStyleSheet("background-color: rgb(248, 248, 248);")
        self.orders.setObjectName("orders")
        self.orders.setColumnCount(3)
        self.orders.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        item.setFont(font)
        self.orders.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        item.setFont(font)
        self.orders.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        item.setFont(font)
        self.orders.setHorizontalHeaderItem(2, item)

        self.retranslateUi(CinHist)
        QtCore.QMetaObject.connectSlotsByName(CinHist)

    def retranslateUi(self, CinHist):
        _translate = QtCore.QCoreApplication.translate
        CinHist.setWindowTitle(_translate("CinHist", "История кинотеатра"))
        item = self.orders.horizontalHeaderItem(0)
        item.setText(_translate("CinHist", "Название"))
        item = self.orders.horizontalHeaderItem(1)
        item.setText(_translate("CinHist", "Места"))
        item = self.orders.horizontalHeaderItem(2)
        item.setText(_translate("CinHist", "Цена"))
