# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_food.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteFood(object):
    def setupUi(self, DeleteFood):
        DeleteFood.setObjectName("DeleteFood")
        DeleteFood.resize(562, 183)
        DeleteFood.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.label = QtWidgets.QLabel(DeleteFood)
        self.label.setGeometry(QtCore.QRect(10, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.name = QtWidgets.QLineEdit(DeleteFood)
        self.name.setGeometry(QtCore.QRect(130, 30, 391, 31))
        self.name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name.setObjectName("name")
        self.delete_2 = QtWidgets.QPushButton(DeleteFood)
        self.delete_2.setGeometry(QtCore.QRect(10, 80, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.delete_2.setFont(font)
        self.delete_2.setAutoFillBackground(False)
        self.delete_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 255, 255), stop:0.373134 rgba(62, 188, 255, 255), stop:0.985075 rgba(0, 0, 255, 255));")
        self.delete_2.setObjectName("delete_2")
        self.menu = QtWidgets.QPushButton(DeleteFood)
        self.menu.setGeometry(QtCore.QRect(10, 120, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.menu.setFont(font)
        self.menu.setAutoFillBackground(False)
        self.menu.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 255, 255), stop:0.373134 rgba(62, 188, 255, 255), stop:0.985075 rgba(0, 0, 255, 255));")
        self.menu.setObjectName("menu")
        self.result = QtWidgets.QLabel(DeleteFood)
        self.result.setGeometry(QtCore.QRect(280, 80, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(9)
        self.result.setFont(font)
        self.result.setStyleSheet("color: rgb(255, 255, 255);")
        self.result.setText("")
        self.result.setObjectName("result")

        self.retranslateUi(DeleteFood)
        QtCore.QMetaObject.connectSlotsByName(DeleteFood)

    def retranslateUi(self, DeleteFood):
        _translate = QtCore.QCoreApplication.translate
        DeleteFood.setWindowTitle(_translate("DeleteFood", "Удалить блюдо"))
        self.label.setText(_translate("DeleteFood", "Название:"))
        self.delete_2.setText(_translate("DeleteFood", "Удалить"))
        self.menu.setText(_translate("DeleteFood", "Просмотреть меню"))
