# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'films.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Films(object):
    def setupUi(self, Films):
        Films.setObjectName("Films")
        Films.resize(695, 579)
        Films.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.films = QtWidgets.QTableWidget(Films)
        self.films.setGeometry(QtCore.QRect(10, 10, 671, 561))
        self.films.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.films.setObjectName("films")
        self.films.setColumnCount(2)
        self.films.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        item.setFont(font)
        self.films.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        item.setFont(font)
        self.films.setHorizontalHeaderItem(1, item)

        self.retranslateUi(Films)
        QtCore.QMetaObject.connectSlotsByName(Films)

    def retranslateUi(self, Films):
        _translate = QtCore.QCoreApplication.translate
        Films.setWindowTitle(_translate("Films", "Фильмы"))
        item = self.films.horizontalHeaderItem(0)
        item.setText(_translate("Films", "Название"))
        item = self.films.horizontalHeaderItem(1)
        item.setText(_translate("Films", "Продолжительность"))
