# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'full_cin_hist.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FullCinHist(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(550, 535)
        Form.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.orders = QtWidgets.QTableWidget(Form)
        self.orders.setGeometry(QtCore.QRect(10, 10, 531, 511))
        self.orders.setMaximumSize(QtCore.QSize(531, 511))
        self.orders.setStyleSheet("background-color: rgb(248, 248, 248);")
        self.orders.setObjectName("orders")
        self.orders.setColumnCount(4)
        self.orders.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        item.setFont(font)
        self.orders.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        item.setFont(font)
        self.orders.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        item.setFont(font)
        self.orders.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        item.setFont(font)
        self.orders.setHorizontalHeaderItem(3, item)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "История кинотеатра"))
        item = self.orders.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Имя"))
        item = self.orders.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Название"))
        item = self.orders.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Места"))
        item = self.orders.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Цена"))
