# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'log.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_log(object):
    def setupUi(self, log):
        log.setObjectName("log")
        log.resize(600, 346)
        log.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.username_login_label = QtWidgets.QLabel(log)
        self.username_login_label.setGeometry(QtCore.QRect(10, 20, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.username_login_label.setFont(font)
        self.username_login_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.username_login_label.setObjectName("username_login_label")
        self.username_login = QtWidgets.QLineEdit(log)
        self.username_login.setGeometry(QtCore.QRect(10, 60, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.username_login.setFont(font)
        self.username_login.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.username_login.setObjectName("username_login")
        self.password_login_label = QtWidgets.QLabel(log)
        self.password_login_label.setGeometry(QtCore.QRect(10, 110, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.password_login_label.setFont(font)
        self.password_login_label.setFocusPolicy(QtCore.Qt.TabFocus)
        self.password_login_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.password_login_label.setObjectName("password_login_label")
        self.password_login = QtWidgets.QLineEdit(log)
        self.password_login.setGeometry(QtCore.QRect(10, 150, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.password_login.setFont(font)
        self.password_login.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.password_login.setObjectName("password_login")
        self.error = QtWidgets.QLabel(log)
        self.error.setGeometry(QtCore.QRect(20, 270, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.error.setFont(font)
        self.error.setStyleSheet("color: rgb(255, 255, 255);")
        self.error.setText("")
        self.error.setObjectName("error")
        self.login_btn = QtWidgets.QPushButton(log)
        self.login_btn.setGeometry(QtCore.QRect(10, 200, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        self.login_btn.setFont(font)
        self.login_btn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 255, 255), stop:0.373134 rgba(62, 188, 255, 255), stop:0.985075 rgba(0, 0, 255, 255));")
        self.login_btn.setObjectName("login_btn")

        self.retranslateUi(log)
        QtCore.QMetaObject.connectSlotsByName(log)

    def retranslateUi(self, log):
        _translate = QtCore.QCoreApplication.translate
        log.setWindowTitle(_translate("log", "Вход"))
        self.username_login_label.setText(_translate("log", "Введите имя пользователя:"))
        self.password_login_label.setText(_translate("log", "Введите пароль:"))
        self.login_btn.setText(_translate("log", "Войти"))
