# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'method.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Choice(object):
    def setupUi(self, Choice):
        Choice.setObjectName("Choice")
        Choice.resize(365, 100)
        Choice.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.add = QtWidgets.QPushButton(Choice)
        self.add.setGeometry(QtCore.QRect(20, 20, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.add.setFont(font)
        self.add.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 255, 255), stop:0.373134 rgba(62, 188, 255, 255), stop:0.985075 rgba(0, 0, 255, 255));")
        self.add.setObjectName("add")
        self.delete_2 = QtWidgets.QPushButton(Choice)
        self.delete_2.setGeometry(QtCore.QRect(200, 20, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.delete_2.setFont(font)
        self.delete_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 255, 255), stop:0.373134 rgba(62, 188, 255, 255), stop:0.985075 rgba(0, 0, 255, 255));")
        self.delete_2.setObjectName("delete_2")

        self.retranslateUi(Choice)
        QtCore.QMetaObject.connectSlotsByName(Choice)

    def retranslateUi(self, Choice):
        _translate = QtCore.QCoreApplication.translate
        Choice.setWindowTitle(_translate("Choice", "Выберите метод"))
        self.add.setText(_translate("Choice", "Добавить\n"
"блюдо"))
        self.delete_2.setText(_translate("Choice", "Удалить блюдо"))
