# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_reg(object):
    def setupUi(self, reg):
        reg.setObjectName("reg")
        reg.resize(430, 638)
        font = QtGui.QFont()
        font.setPointSize(14)
        reg.setFont(font)
        reg.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.password_label = QtWidgets.QLabel(reg)
        self.password_label.setGeometry(QtCore.QRect(10, 90, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.password_label.setFont(font)
        self.password_label.setStyleSheet("color: rgb(255, 253, 251);")
        self.password_label.setObjectName("password_label")
        self.email = QtWidgets.QLineEdit(reg)
        self.email.setGeometry(QtCore.QRect(10, 310, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.email.setFont(font)
        self.email.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.email.setObjectName("email")
        self.error = QtWidgets.QLabel(reg)
        self.error.setGeometry(QtCore.QRect(20, 420, 371, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.error.setFont(font)
        self.error.setStyleSheet("color: rgb(255, 253, 251);")
        self.error.setText("")
        self.error.setObjectName("error")
        self.email_label = QtWidgets.QLabel(reg)
        self.email_label.setGeometry(QtCore.QRect(10, 270, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.email_label.setFont(font)
        self.email_label.setStyleSheet("color: rgb(255, 253, 251);")
        self.email_label.setObjectName("email_label")
        self.password = QtWidgets.QLineEdit(reg)
        self.password.setGeometry(QtCore.QRect(10, 130, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.password.setFont(font)
        self.password.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.password.setObjectName("password")
        self.password_correct_label = QtWidgets.QLabel(reg)
        self.password_correct_label.setGeometry(QtCore.QRect(10, 180, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.password_correct_label.setFont(font)
        self.password_correct_label.setStyleSheet("color: rgb(255, 253, 251);")
        self.password_correct_label.setObjectName("password_correct_label")
        self.username_label = QtWidgets.QLabel(reg)
        self.username_label.setGeometry(QtCore.QRect(10, 10, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.username_label.setFont(font)
        self.username_label.setStyleSheet("color: rgb(255, 253, 251);")
        self.username_label.setObjectName("username_label")
        self.password_correct = QtWidgets.QLineEdit(reg)
        self.password_correct.setGeometry(QtCore.QRect(10, 220, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.password_correct.setFont(font)
        self.password_correct.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.password_correct.setObjectName("password_correct")
        self.register_btn = QtWidgets.QPushButton(reg)
        self.register_btn.setGeometry(QtCore.QRect(10, 360, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.register_btn.setFont(font)
        self.register_btn.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 255, 255), stop:0.373134 rgba(62, 188, 255, 255), stop:0.985075 rgba(0, 0, 255, 255));")
        self.register_btn.setObjectName("register_btn")
        self.username = QtWidgets.QLineEdit(reg)
        self.username.setGeometry(QtCore.QRect(10, 50, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(14)
        self.username.setFont(font)
        self.username.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.username.setObjectName("username")

        self.retranslateUi(reg)
        QtCore.QMetaObject.connectSlotsByName(reg)

    def retranslateUi(self, reg):
        _translate = QtCore.QCoreApplication.translate
        reg.setWindowTitle(_translate("reg", "Регистрация"))
        self.password_label.setText(_translate("reg", "Введите пароль:"))
        self.email_label.setText(_translate("reg", "Введите ваш email:"))
        self.password_correct_label.setText(_translate("reg", "Подтвердите пароль:"))
        self.username_label.setText(_translate("reg", "Введите имя пользователя:"))
        self.register_btn.setText(_translate("reg", "Зарегистрироваться"))
