# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'users_database.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserBase(object):
    def setupUi(self, UserBase):
        UserBase.setObjectName("UserBase")
        UserBase.resize(548, 532)
        UserBase.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.users = QtWidgets.QTableWidget(UserBase)
        self.users.setGeometry(QtCore.QRect(10, 10, 531, 511))
        self.users.setMaximumSize(QtCore.QSize(531, 511))
        self.users.setStyleSheet("background-color: rgb(248, 248, 248);")
        self.users.setObjectName("users")
        self.users.setColumnCount(4)
        self.users.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        item.setFont(font)
        self.users.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        item.setFont(font)
        self.users.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        item.setFont(font)
        self.users.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        item.setFont(font)
        self.users.setHorizontalHeaderItem(3, item)

        self.retranslateUi(UserBase)
        QtCore.QMetaObject.connectSlotsByName(UserBase)

    def retranslateUi(self, UserBase):
        _translate = QtCore.QCoreApplication.translate
        UserBase.setWindowTitle(_translate("UserBase", "Все пользователи"))
        item = self.users.horizontalHeaderItem(0)
        item.setText(_translate("UserBase", "Id"))
        item = self.users.horizontalHeaderItem(1)
        item.setText(_translate("UserBase", "Имя"))
        item = self.users.horizontalHeaderItem(2)
        item.setText(_translate("UserBase", "Пароль"))
        item = self.users.horizontalHeaderItem(3)
        item.setText(_translate("UserBase", "email"))
